// Generated by Wrangler on Sat May 11 2024 18:22:38 GMT-0300 (Horário Padrão de Brasília)
// by running `wrangler types`

type Env = {
  MEMELAND_SEARCH: KVNamespace;
  MEMELAND_STORAGE: R2Bucket;
  STORAGE_BASE: string;
  SUPABASE_STORAGE_ENDPOINT: string;
  SUPABASE_STORAGE_BASE: string;
  SUPABASE_STORAGE_ACCESS_KEY_ID: string;
  SUPABASE_STORAGE_SECRET_ACCESS_KEY: string;
  SUPABASE_PROJECT_URL: string;
  SUPABASE_ANON_KEY: string;
  OPENAI_API_KEY: string;
};
