// Generated by Wrangler on Sat May 11 2024 18:22:38 GMT-0300 (Horário Padrão de Brasília)
// by running `wrangler types`

type Env = {
  AI: Ai;
  VECTORIZE: Vectorize;
  MEMELAND_SEARCH: KVNamespace;
  MEMELAND_STORAGE: R2Bucket;
  DB: D1Database;
  STORAGE_BASE: string;
  SUPABASE_STORAGE_ENDPOINT: string;
  SUPABASE_STORAGE_BASE: string;
  SUPABASE_STORAGE_ACCESS_KEY_ID: string;
  SUPABASE_STORAGE_SECRET_ACCESS_KEY: string;
  SUPABASE_PROJECT_URL: string;
  SUPABASE_ANON_KEY: string;
  OPENAI_API_KEY: string;
  CLOUDFLARE_ACCOUNT_ID: string;
  CLOUDFLARE_API_KEY: string;
  GITHUB_CLIENT_ID: string;
  GITHUB_CLIENT_SECRET: string;
  GITHUB_REDIRECT_URI: string;
};
