// Generated by Wrangler on Sun Apr 28 2024 19:38:09 GMT-0300 (Horário Padrão de Brasília)
// by running `wrangler types`

type Env = {
  SUPABASE_STORAGE_ENDPOINT: string;
  SUPABASE_STORAGE_ACCESS_KEY_ID: string;
  SUPABASE_STORAGE_SECRET_ACCESS_KEY: string;
  SUPABASE_PROJECT_URL: string;
  SUPABASE_ANON_KEY: string;
  OPENAI_API_KEY: string;
};
